2025-03-22 12:08:59,532 INFO    MainThread:5816 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-22 12:08:59,532 INFO    MainThread:5816 [wandb_setup.py:_flush():67] Configure stats pid to 5816
2025-03-22 12:08:59,532 INFO    MainThread:5816 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Jonas\.config\wandb\settings
2025-03-22 12:08:59,532 INFO    MainThread:5816 [wandb_setup.py:_flush():67] Loading settings from c:\nlp_1\notebooks\wandb\settings
2025-03-22 12:08:59,532 INFO    MainThread:5816 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-22 12:08:59,533 INFO    MainThread:5816 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\nlp_1\notebooks\wandb\run-20250322_120859-c326kvy7\logs\debug.log
2025-03-22 12:08:59,534 INFO    MainThread:5816 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\nlp_1\notebooks\wandb\run-20250322_120859-c326kvy7\logs\debug-internal.log
2025-03-22 12:08:59,534 INFO    MainThread:5816 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000225235191B0>
2025-03-22 12:08:59,539 INFO    MainThread:5816 [wandb_init.py:init():761] calling init triggers
2025-03-22 12:08:59,539 INFO    MainThread:5816 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-22 12:08:59,539 INFO    MainThread:5816 [wandb_init.py:init():784] starting backend
2025-03-22 12:08:59,539 INFO    MainThread:5816 [wandb_init.py:init():788] sending inform_init request
2025-03-22 12:08:59,607 INFO    MainThread:5816 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-03-22 12:08:59,608 INFO    MainThread:5816 [wandb_init.py:init():798] backend started and connected
2025-03-22 12:08:59,613 INFO    MainThread:5816 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-22 12:08:59,630 INFO    MainThread:5816 [wandb_init.py:init():891] updated telemetry
2025-03-22 12:08:59,753 INFO    MainThread:5816 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-22 12:09:00,479 INFO    MainThread:5816 [wandb_init.py:init():990] starting run threads in backend
2025-03-22 12:09:00,868 INFO    MainThread:5816 [wandb_run.py:_console_start():2375] atexit reg
2025-03-22 12:09:00,869 INFO    MainThread:5816 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-22 12:09:00,869 INFO    MainThread:5816 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-22 12:09:00,869 INFO    MainThread:5816 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-22 12:09:00,883 INFO    MainThread:5816 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-22 12:09:00,889 INFO    MainThread:5816 [wandb_run.py:_config_callback():1261] config_cb None None {'embedding_dim': 300, 'hidden_dim': 128, 'output_dim': 5, 'learning_rate': 0.001, 'batch_size': 16}
2025-03-22 12:09:00,890 INFO    MainThread:5816 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-22 12:09:00,890 INFO    MainThread:5816 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-22 12:09:03,499 INFO    MainThread:5816 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-22 12:09:11,941 INFO    MainThread:5816 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-22 12:09:11,941 INFO    MainThread:5816 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-22 12:09:12,986 INFO    MainThread:5816 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-22 12:09:12,991 INFO    MainThread:5816 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-22 12:09:12,991 INFO    MainThread:5816 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-22 12:09:15,115 INFO    MainThread:5816 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-22 12:09:19,287 INFO    MainThread:5816 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-22 12:09:19,287 INFO    MainThread:5816 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-22 13:27:23,842 WARNING MsgRouterThr:5816 [router.py:message_loop():63] message_loop has been closed
Traceback (most recent call last):
  File "c:\nlp_1\.venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 208, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\nlp_1\.venv\lib\site-packages\wandb\sdk\interface\router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "c:\nlp_1\.venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "c:\nlp_1\.venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 212, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\nlp_1\.venv\lib\site-packages\wandb\sdk\interface\router.py", line 56, in message_loop
    msg = self._read_message()
  File "c:\nlp_1\.venv\lib\site-packages\wandb\sdk\interface\router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-22 13:27:24,122 INFO    MsgRouterThr:5816 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
